# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 06:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('user_profile', '0003_auto_20160408_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('homepage', models.URLField()),
                ('name', models.CharField(max_length=30)),
                ('strength', models.IntegerField(default=2)),
                ('intellegent', models.IntegerField(default=2)),
                ('swiftness', models.IntegerField(default=2)),
                ('diplonacy', models.IntegerField(default=2)),
                ('militant', models.IntegerField(default=2)),
                ('my_image', models.ImageField(upload_to=b'media')),
            ],
        ),
    ]
