# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='diplonacy',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='intellegent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='militant',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='my_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='swiftness',
        ),
    ]
