# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PStartStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('strength', models.IntegerField(default=2)),
                ('intellegent', models.IntegerField(default=2)),
                ('swiftness', models.IntegerField(default=2)),
                ('diplonacy', models.IntegerField(default=2)),
                ('militant', models.IntegerField(default=2)),
            ],
        ),
    ]
