# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0002_auto_20160403_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(max_length=250, upload_to='uploads/flatpictures')),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('info', models.TextField()),
            ],
        ),
    ]
