# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0003_flatpicture_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatPicture',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
