# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygame', '0004_auto_20160407_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characters',
            name='diplonacy',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='intellegent',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='militant',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='name',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='characters',
            name='swiftness',
        ),
    ]
